#============================================================#
#                    Plugin By GodWeedZao                    #
#============================================================#
# ╔═╗╔═╗    ╔╗ ╔╗    ╔═══╗    ╔╗         ╔═══╗╔╗       ╔╗   #
# ║║╚╝║║    ║║╔╝╚╗   ║╔═╗║    ║║         ║╔═╗║║║      ╔╝╚╗  #
# ║╔╗╔╗║╔╗╔╗║║╚╗╔╝╔╗ ║║ ╚╝╔══╗║║ ╔══╗╔═╗ ║║ ╚╝║╚═╗╔══╗╚╗╔╝  #
# ║║║║║║║║║║║║ ║║ ╠╣ ║║ ╔╗║╔╗║║║ ║╔╗║║╔╝ ║║ ╔╗║╔╗║╚ ╗║ ║║   #
# ║║║║║║║╚╝║║╚╗║╚╗║║ ║╚═╝║║╚╝║║╚╗║╚╝║║║  ║╚═╝║║║║║║╚╝╚╗║╚╗  #
# ╚╝╚╝╚╝╚══╝╚═╝╚═╝╚╝ ╚═══╝╚══╝╚═╝╚══╝╚╝  ╚═══╝╚╝╚╝╚═══╝╚═╝  #
#============================================================#
#    Report: https://Github.com/GodWeedZao/MultiColorChat    #
#============================================================#
#You can change MultiColor parameters (Color formats) to what ever you want!
MultiColor: ['§l', '§a', '§2', '§c', '§4', '§e', '§6', '§d', '§5', '§b', '§3']